apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: c1
        image: saidinesh12/react-app
        ports:
        - containerPort: 80
---  
apiVersion: v1
kind: Service
metadata:
  name: lms-service
spec:
  type: LoadBalancer
  selector:
    app: lms
  ports:
    - port: 80     